### ISSUE TITLE
Factory

### ISSUE THREAD

**Issue by guarrasi1995** [AndreaScazzeri/Progetto_Stratified_Shuffle_Split_23-24#10]
La presenza di una factory per gestire la creazione degli splitter è un'ottima pratica, poiché astrae i dettagli di creazione degli oggetti specifici e facilita l'estensibilità del codice. Tuttavia, l'opzione "both" che restituisce una tupla di splitter sembra essere una deviazione dal principio di singola responsabilità, poiché modifica il tipo di ritorno atteso basandosi sui parametri di input.

Assicurarsi che tutti i metodi di splitting restituiscano oggetti che condividano un'interfaccia comune.

**Comment by RealMattio** [comment]
Abbiamo inserito un ciclo sulla tupla che eventualmente la factory potrebbe restituire. In questo modo rimane compito della factory fornire tutti gli splitter necessari anche se dovesse essere solo uno. Il resto del programma rimarrà indipendente da questo, al più itererà più volte.
Il commit di riferimento è https://github.com/AndreaScazzeri/Progetto_Stratified_Shuffle_Split_23-24/commit/4da8e92d890b164a6e0812300fb747d371dd45f5
Non chiudo la issue per rimanere a disposizioni su altre eventuali osservazioni.

**Comment by RealMattio** [comment]
Per un errore nel commit precedente non era stata inserito anche la modifica della factory, ora è presente anche quella (https://github.com/AndreaScazzeri/Progetto_Stratified_Shuffle_Split_23-24/commit/ed8de368f0d019a9ad9dd28f8f0372a541f0596d)
