### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by guarrasi1995** [AndreaScazzeri/Progetto_Stratified_Shuffle_Split_23-24#11]
Attualmente, il programma tenta di salvare i grafici generati nella cartella Plots, ma se questa cartella non esiste già, l'operazione fallisce, causando un errore. Questo richiede agli utenti di creare manualmente la cartella prima di eseguire il programma, un passaggio che non è intuitivo.

Modificare il programma in modo che controlli l'esistenza della cartella Plots al momento del salvataggio dei grafici e, se non presente, la crei automaticamente.

**Comment by RealMattio** [comment]
Avendo già creato tutti la cartella non avevamo messo in conto questa situazione. Abbiamo provveduto a risolvere il problema con questo commit https://github.com/AndreaScazzeri/Progetto_Stratified_Shuffle_Split_23-24/commit/ee4d8dc515929ea5a569103ddff23a4e6c11e131
Grazie per la segnalazione!
