### ISSUE TITLE
Input Utente

### ISSUE THREAD

**Issue by guarrasi1995** [AndreaScazzeri/Progetto_Stratified_Shuffle_Split_23-24#9]
Attualmente, la configurazione dei parametri di esecuzione del programma richiede la modifica diretta del codice sorgente. Questo approccio limita l'accessibilità del programma agli utenti che non sono a loro agio con la programmazione e complica il processo di esperimentazione con diverse configurazioni.

Implementare una funzionalità che permetta agli utenti di inserire i parametri di esecuzione in modo interattivo all'avvio del programma. Utilizzare input() per raccogliere input direttamente dall'utente durante l'esecuzione interattiva. Assicurarsi che per ogni input richiesto, vengano fornite istruzioni chiare e opzioni di default dove possibile. Implementare la validazione degli input per garantire che i valori inseriti siano appropriati per i parametri richiesti.

**Comment by AndreaScazzeri** [comment]
Abbiamo implementato lo script Input.py (commit: https://github.com/AndreaScazzeri/Progetto_Stratified_Shuffle_Split_23-24/commit/b5b7b10740d45002bc598f1f49b4e154f2cd0671)  per risolvere l'issue da lei esposta.
Rimaniamo a disposizione senza chiudere la issue per eventuali problemi.
